window.EXPENSE_DATA = [
  {
    "date": "2026-03-08",
    "vendor": "Лента",
    "category": "Продукты",
    "subcategory": "Готовая еда",
    "item": "Сосиска в тесте",
    "quantity": 2.0,
    "unit_price_rub": 59.99,
    "line_total_rub": 119.98,
    "vat_rate": "10%",
    "payment_method": "МИР · карта Лента",
    "receipt_id": "0118 / 0080326.0129",
    "notes": ""
  },
  {
    "date": "2026-03-08",
    "vendor": "Лента",
    "category": "Продукты",
    "subcategory": "Выпечка",
    "item": "Слойка с сыром",
    "quantity": 2.0,
    "unit_price_rub": 74.99,
    "line_total_rub": 149.98,
    "vat_rate": "10%",
    "payment_method": "МИР · карта Лента",
    "receipt_id": "0118 / 0080326.0129",
    "notes": ""
  },
  {
    "date": "2026-03-08",
    "vendor": "Лента",
    "category": "Продукты",
    "subcategory": "Напитки безалк.",
    "item": "Напиток б/а EV",
    "quantity": 1.0,
    "unit_price_rub": 94.99,
    "line_total_rub": 94.99,
    "vat_rate": "22%",
    "payment_method": "МИР · карта Лента",
    "receipt_id": "0118 / 0080326.0129",
    "notes": ""
  },
  {
    "date": "2026-03-08",
    "vendor": "Лента",
    "category": "Продукты",
    "subcategory": "Алкоголь",
    "item": "Вино игристое",
    "quantity": 1.0,
    "unit_price_rub": 559.99,
    "line_total_rub": 559.99,
    "vat_rate": "22%",
    "payment_method": "МИР · карта Лента",
    "receipt_id": "0118 / 0080326.0129",
    "notes": ""
  },
  {
    "date": "2026-03-08",
    "vendor": "Лента",
    "category": "Продукты",
    "subcategory": "Напитки безалк.",
    "item": "Сок садовый",
    "quantity": 1.0,
    "unit_price_rub": 189.99,
    "line_total_rub": 189.99,
    "vat_rate": "10%",
    "payment_method": "МИР · карта Лента",
    "receipt_id": "0118 / 0080326.0129",
    "notes": ""
  },
  {
    "date": "2026-03-08",
    "vendor": "Лента",
    "category": "Продукты",
    "subcategory": "Напитки безалк.",
    "item": "Напиток б/а «Черноголовка»",
    "quantity": 1.0,
    "unit_price_rub": 109.99,
    "line_total_rub": 109.99,
    "vat_rate": "22%",
    "payment_method": "МИР · карта Лента",
    "receipt_id": "0118 / 0080326.0129",
    "notes": ""
  },
  {
    "date": "2026-03-08",
    "vendor": "Лента",
    "category": "Продукты",
    "subcategory": "Выпечка",
    "item": "Сочень с творогом",
    "quantity": 2.0,
    "unit_price_rub": 52.1,
    "line_total_rub": 104.2,
    "vat_rate": "10%",
    "payment_method": "МИР · карта Лента",
    "receipt_id": "0118 / 0080326.0129",
    "notes": ""
  },
  {
    "date": "2026-03-08",
    "vendor": "Лента",
    "category": "Продукты",
    "subcategory": "Хлеб",
    "item": "Горбушка сдобная",
    "quantity": 2.0,
    "unit_price_rub": 129.99,
    "line_total_rub": 259.98,
    "vat_rate": "10%",
    "payment_method": "МИР · карта Лента",
    "receipt_id": "0118 / 0080326.0129",
    "notes": ""
  },
  {
    "date": "2026-03-08",
    "vendor": "Лента",
    "category": "Продукты",
    "subcategory": "Хлеб",
    "item": "Горбушка сдобная",
    "quantity": 2.0,
    "unit_price_rub": 129.99,
    "line_total_rub": 259.98,
    "vat_rate": "10%",
    "payment_method": "МИР · карта Лента",
    "receipt_id": "0118 / 0080326.0129",
    "notes": "Второй артикул того же товара"
  },
  {
    "date": "2026-03-08",
    "vendor": "Лента",
    "category": "Инфо",
    "subcategory": "Лояльность",
    "item": "Сводка скидки",
    "quantity": 1.0,
    "unit_price_rub": null,
    "line_total_rub": 0.0,
    "vat_rate": "",
    "payment_method": "МИР · карта Лента",
    "receipt_id": "0118 / 0080326.0129",
    "notes": "Скидка по карте Лента: 298.22 руб (информация от магазина). Оригинал чека: finance/receipts/2026-03-08-lenta.jpg"
  },
  {
    "date": "2026-03-09",
    "vendor": "Т2",
    "category": "Связь",
    "subcategory": "Мобильная связь",
    "item": "Оплата Tele2 (личная связь)",
    "quantity": 1.0,
    "unit_price_rub": 901.0,
    "line_total_rub": 901.0,
    "vat_rate": "20%",
    "payment_method": "Сбербанк карта",
    "receipt_id": "",
    "notes": "Скриншот Сбера: finance/receipts/2026-03-09-sber-tele2.jpg"
  },
  {
    "date": "2026-03-08",
    "vendor": "Лента",
    "category": "Продукты",
    "subcategory": "Супермаркет",
    "item": "Покупка продуктов (Сбербанк без детализации)",
    "quantity": 1.0,
    "unit_price_rub": 2875.95,
    "line_total_rub": 2875.95,
    "vat_rate": "",
    "payment_method": "Сбербанк карта",
    "receipt_id": "",
    "notes": "Скриншот Сбера: finance/receipts/2026-03-08-sber-lenta-2875.jpg"
  },
  {
    "date": "2026-03-09",
    "vendor": "Магнит Лепорелло",
    "category": "Продукты",
    "subcategory": "Алкоголь",
    "item": "Пиво Янтарная Бочка светлое 4.7%",
    "quantity": 3.0,
    "unit_price_rub": 113.99,
    "line_total_rub": 341.97,
    "vat_rate": "20%",
    "payment_method": "Безнал (Сбербанк)",
    "receipt_id": "ФД 247481015",
    "notes": "Скан: finance/receipts/2026-03-09-magnit-leporello.jpg"
  },
  {
    "date": "2026-03-09",
    "vendor": "Магнит Лепорелло",
    "category": "Продукты",
    "subcategory": "Молочные продукты",
    "item": "Простоквашино молоко пастеризованное 2.5% 0.93л",
    "quantity": 1.0,
    "unit_price_rub": 83.99,
    "line_total_rub": 83.99,
    "vat_rate": "10%",
    "payment_method": "Безнал (Сбербанк)",
    "receipt_id": "ФД 247481015",
    "notes": ""
  },
  {
    "date": "2026-03-09",
    "vendor": "Магнит Лепорелло",
    "category": "Продукты",
    "subcategory": "Молочные продукты",
    "item": "Простоквашино кефир 3.2% 0.93л",
    "quantity": 1.0,
    "unit_price_rub": 99.99,
    "line_total_rub": 99.99,
    "vat_rate": "10%",
    "payment_method": "Безнал (Сбербанк)",
    "receipt_id": "ФД 247481015",
    "notes": ""
  },
  {
    "date": "2026-03-09",
    "vendor": "Магнит Лепорелло",
    "category": "Продукты",
    "subcategory": "Бакалея",
    "item": "Лапша Доширак куриная 90г",
    "quantity": 1.0,
    "unit_price_rub": 56.99,
    "line_total_rub": 56.99,
    "vat_rate": "20%",
    "payment_method": "Безнал (Сбербанк)",
    "receipt_id": "ФД 247481015",
    "notes": ""
  },
  {
    "date": "2026-03-09",
    "vendor": "Магнит Лепорелло",
    "category": "Продукты",
    "subcategory": "Молочные продукты",
    "item": "Простоквашино сметана 20% 300г",
    "quantity": 1.0,
    "unit_price_rub": 99.99,
    "line_total_rub": 99.99,
    "vat_rate": "10%",
    "payment_method": "Безнал (Сбербанк)",
    "receipt_id": "ФД 247481015",
    "notes": ""
  },
  {
    "date": "2026-03-09",
    "vendor": "Магнит Лепорелло",
    "category": "Продукты",
    "subcategory": "Заготовки",
    "item": "Капуста квашеная 500г",
    "quantity": 1.0,
    "unit_price_rub": 103.99,
    "line_total_rub": 103.99,
    "vat_rate": "10%",
    "payment_method": "Безнал (Сбербанк)",
    "receipt_id": "ФД 247481015",
    "notes": ""
  },
  {
    "date": "2026-03-09",
    "vendor": "Магнит Лепорелло",
    "category": "Продукты",
    "subcategory": "Молочные напитки",
    "item": "Чудо коктейль клубничный 2% 0.2л",
    "quantity": 2.0,
    "unit_price_rub": 43.99,
    "line_total_rub": 87.98,
    "vat_rate": "10%",
    "payment_method": "Безнал (Сбербанк)",
    "receipt_id": "ФД 247481015",
    "notes": ""
  },
  {
    "date": "2026-03-09",
    "vendor": "Магнит Лепорелло",
    "category": "Продукты",
    "subcategory": "Мясные деликатесы",
    "item": "Зельц Деревенский вареный свиной 0.5кг",
    "quantity": 1.0,
    "unit_price_rub": 149.99,
    "line_total_rub": 149.99,
    "vat_rate": "",
    "payment_method": "Безнал (Сбербанк)",
    "receipt_id": "ФД 247481015",
    "notes": ""
  },
  {
    "date": "2026-03-09",
    "vendor": "Магнит Лепорелло",
    "category": "Продукты",
    "subcategory": "Сладости",
    "item": "Kinder Pingui пирожное",
    "quantity": 2.0,
    "unit_price_rub": 69.99,
    "line_total_rub": 139.98,
    "vat_rate": "20%",
    "payment_method": "Безнал (Сбербанк)",
    "receipt_id": "ФД 247481015",
    "notes": ""
  }
]
